# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017 # For debugging with R/mongolite, not needed by cranlike.
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cranlike:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      CRANLIKE_MONGODB_USERNAME: root
      CRANLIKE_MONGODB_PASSWORD: example

volumes:
  mongo-data:
